name: Azure Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep templates
      run: |
        az deployment group create \
          --resource-group crmappapi \
          --template-file bicep/main.bicep \
          --parameters \
            appServiceName=CRMAppService \
            appServicePlanName=CRMAppServicePlan \
            cosmosDbAccountName=CRMCosmosDb \
            databaseName=CRMDatabase \
            containerName=CRMData
